apiVersion: apps/v1
kind: Deployment
metadata:
  name: datriweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datriweb
  template:
    metadata:
      labels:
        app: datriweb
    spec:
      containers:
        - name: datriweb
          image: yourdockerhubusername/datriweb:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: datriuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: db_password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: app_key
