containers:
  - name: datriweb
    image: datricon/datriweb:latest
    ports:
      - containerPort: 9000
    command: ["/bin/sh", "-c"]
    args:
      - |
        cp .env.example .env &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan optimize &&
        php-fpm
    env:
      - name: DB_HOST
        value: mysql
      - name: DB_DATABASE
        value: laravel
      - name: DB_USERNAME
        value: datriuser
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: laravel-secrets
            key: db_password
      - name: APP_KEY
        valueFrom:
          secretKeyRef:
            name: laravel-secrets
            key: app_key
